[project]
name = "hw05"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Almukhan Omarov", email = "almukha.fly@gmail.com"},
]
dependencies = []
requires-python = "==3.9.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
